fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.3.101'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.3.101'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.3.101'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.3.101'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.3.101'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1587403922.68-14323-275321543540677/AnsiballZ_purefa_host.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1587403922.68-14323-275321543540677/AnsiballZ_purefa_host.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1587403922.68-14323-275321543540677/AnsiballZ_purefa_host.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_host', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purefa_host_payload_b5nranhg/ansible_purefa_host_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_host.py\", line 634, in <module>\n  File \"/tmp/ansible_purefa_host_payload_b5nranhg/ansible_purefa_host_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_host.py\", line 584, in main\n  File \"/tmp/ansible_purefa_host_payload_b5nranhg/ansible_purefa_host_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_host.py\", line 242, in _is_cbs\n  File \"/usr/local/lib/python3.6/site-packages/purestorage/purestorage.py\", line 1742, in get_hardware\n    return self._request(\"GET\", \"hardware/{0}\".format(component), kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/purestorage/purestorage.py\", line 198, in _request\n    raise PureHTTPError(self._target, str(self._rest_version), response)\npurestorage.purestorage.PureHTTPError: PureHTTPError status code 400 returned by REST version 1.16 at 172.16.3.101: BAD REQUEST\n[{\"msg\": \"No such element exists.\", \"code\": 0}]\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
